server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          test:
            provider: spring
            client-id: test
            client-secret: 123456
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/{registrationId}"
            scope: openid,message.read,message.write
        provider:
          spring:
            issuer-uri: http://localhost:9000
            authorization-uri: http://localhost:9000/my/authorize

messages:
  base-uri: http://127.0.0.1:8090/messages
